package io.github.ykwyuta.llmmock.usage;

/**
 * Where an answer came from. This is what separates money actually spent from money the
 * cache saved.
 */
public enum UsageSource {

    /** A real upstream call. This is the spend that actually happened. */
    UPSTREAM,

    /** A cache hit in {@code CACHED_PROXY}: these tokens would have cost money. */
    CACHE,

    /** A recording replayed offline in {@code REPLAY}. */
    RECORDING,

    /** Generated by the stub engine. The counts are synthetic. */
    MOCK
}
